//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyFormsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public int ID { get; set; }
        public string CompanyName { get; set; }
        public string Location { get; set; }
        public Nullable<int> EmployeeNumber { get; set; }
        public Nullable<int> OwnerId { get; set; }
    
        public virtual Owner Owner { get; set; }
    }
}
